CREATE TABLE authors (
  first_name varchar(100),
  last_name varchar(100)
);

CREATE TABLE games (
  id int unique generated by default as identity,
  publish_date int,
  archived boolean,
  multiplayer boolean,
  last_played_at int,
  FOREIGN KEY item_id references item(id)
);