CREATE TABLE genre (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255)
);

CREATE TABLE author (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255)
);

CREATE TABLE label (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR(255),
	color VARCHAR(255)
);

CREATE TABLE item (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	genre_id INT,
	author_id INT,
	label_id INT,
	public_date DATE,
	archived BOOLEAN,
	FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE book(
	id INT NOT NULL,
	publisher VARCHAR(255),
	cover_state VARCHAR(255),
	FOREIGN KEY (id) REFERENCES item (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE music_album(
	id INT NOT NULL,
	on_spotify BOOLEAN,
	FOREIGN KEY (id) REFERENCES item (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE game(
	id INT NOT NULL,
	multiplayer BOOLEAN,
	last_played_at DATE,
	FOREIGN KEY (id) REFERENCES item (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
